name: Update Github Profile With Weather Info

on:
  push:
    branches: master
  schedule:
    - cron: "0 */3 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.mjs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GAODE_KEY: ${{ secrets.GAODE_KEY }}
          CITY_ATCODE: 360300