name: Update Github Profile With Weather Info

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Update Github Profile
        run: node ./index.mjs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GAODE_KEY: ${{ secrets.GAODE_KEY }}
          CITY_ATCODE: 360300